pipeline {
    agent none // no global agent
    stages {
        stage('Build') {
            agent {
                docker {
                    image 'python:2-alpine'
                }
            }
            steps {
                sh 'python -m py_compile sources/add2vals.py sources/calc.py'
            }
        }
        stage('Test') {
            agent {
                docker {
                    image 'qnib/pytest'
                }
            }
            steps {
                sh 'py.test --verbose --junit-xml test-reports/results.xml sources/test_calc.py'
            }
            post { // happens afer the steps
                always { // will execute no matter what. Could also be success, failure or unstable
                    junit 'test-reports/results.xml'
                }
            }
        }
    }
}
